# Generated by Django 3.2 on 2021-05-04 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
