# Generated by Django 3.2 on 2021-05-07 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0003_rename_password_contract_descp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='descp',
            field=models.CharField(max_length=122),
        ),
    ]
