# Generated by Django 3.2 on 2021-05-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0004_auto_20210507_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='rate',
            new_name='rating',
        ),
    ]
