# Generated by Django 3.2 on 2021-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0005_rename_rate_contract_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rating',
            field=models.TextField(),
        ),
    ]
