# Generated by Django 3.2 on 2021-05-07 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0008_alter_contract_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rating',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
