# Generated by Django 3.2 on 2021-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0009_alter_contract_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
