# Generated by Django 3.2 on 2021-05-08 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0010_alter_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='avtar',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
